### PR TITLE
Vue 3 support

### LINKED ISSUE #139: Vue 3 support
@kazupon, is there planning Vue 3 support for this repo?

Now it requires the `vue-template-compiler` package, which is deprecated in Vue 3, so when using `
vue-i18n-locale-message` with Vue 3 version mismatch error is thrown

### PR DESCRIPTION
**Pull request by ardier16**
### Changed:
- replace `vue-template-compiler` with `@vue/compiler-sfc`
- upgrade `vue` to version `3.0.11`
- upgrade demo to Vue 3

@kazupon IMO it should be merged into `next` branch, and released as `next` version

Closes #139

### CODE REVIEW

**Comment by kazupon** [comment]
@ardier16 
I am very happy to you for your Vue 3 support.
We are planning to release vue-i18n-locale-message v1 first for Vue3 support.
After releasing that, we hope to provide a Vue 3 support version.

I would like you to send me your PR at that time.

**Comment by kazupon** [comment]
@ardier16 
Hi! I've just released v1 for Vue 2
I think I'll release v2 for Vue 3.
Could you resolve the conflict of this PR! 🙏

**Comment by ardier16** [comment]
> @ardier16
> Hi! I've just released v1 for Vue 2
> I think I'll release v2 for Vue 3.
> Could you resolve the conflict of this PR! 🙏

Hi, @kazupon!
Just resolved a conflict, it's ready to be merged.
Is there a `next` branch for this PR?

**Comment by kazupon** [comment]
@ardier16 
Your PR is OK.
Thank you so much!

**Pull request merged**
