### PR TITLE
feat: Add ignorePath option in cli (infuse, squeeze)

### PR DESCRIPTION
**Pull request by kiibo382**
fix: #149 
add ignorePath to yargs.
add 'ignore' (npm package), and make sure to load .ignore file.

### CODE REVIEW

**Comment by kazupon** [comment]
@kiibo382 
At first, We need to release Vue v2.x  for our biz requirements.

This repo has a `maintain-v1` branch.
You can modify it.

**Comment by kiibo382** [comment]
Oh..
Sorry. I modify it.

**Comment by kazupon** [comment]
No problem. 
It's my bad that I don’t write docs about it.

**Comment by kazupon** [comment]
I've just `cherry-pick`ed  to `master` (v2 branch) now.
https://github.com/intlify/vue-i18n-locale-message/commit/662a2a321825bbf9148f1cd20128d7e12adc8975

so close.
Thanks!

**Pull request closed without merging**
